# Generated by Django 2.2 on 2019-04-23 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Datos',
            fields=[
                ('Temperatura', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Humedad', models.CharField(max_length=100)),
                ('Direccion del viento', models.TextField(blank=True, null=True)),
                ('Presion atmosferica', models.BooleanField(default=False)),
            ],
        ),
    ]
