# Generated by Django 2.2 on 2019-07-19 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ara_project_web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Datos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperatura', models.CharField(max_length=100)),
                ('presion_atm', models.CharField(max_length=100)),
                ('humedad', models.CharField(max_length=100)),
                ('dir_viento', models.CharField(max_length=100)),
            ],
        ),
    ]
