# Generated by Django 2.2.3 on 2019-07-23 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ara_project_web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='datos',
            name='dir_viento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='datos',
            name='humedad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='datos',
            name='presion_atm',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='datos',
            name='temperatura',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
