# Generated by Django 2.2.3 on 2019-07-23 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ara_project_web', '0002_auto_20190723_0026'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datos',
            options={'verbose_name_plural': 'Datos'},
        ),
    ]
